### ANKexplorer: Exploring the diversity of ANK repeats in the Podospora anserina species complex
# ===========================================================================
# Sandra Lorena Ament Velasquez
# 2024-08-13
# ++++++++++++++++++++++++++++++++++++++++++++++

# Input files
basealignment: "data/2025.04.14_hnwd_master_onlyWDdomain_NWDs_noGuides_noemptycols_4paper.fa" # for all NWD genes (including HNWDs) in P. anserina (excluding NWD4, which is not closely related)

# Scripts
descriptor: "../JustHetGenes/scripts/WDdescriptor.py"
WD40s_PCA: "scripts/WD40s_PCA_paralog.R"
WD40s_LOGOS: "scripts/WD40s_LOGOS.R"

## Variables
# The amino acid positions used to classify the repeats (influenced by the REGEX definition of the repeat)
AMINOS: '10-11-12-14-30-32-39' # coordinates of WD40 Repeat as in Hu et al. (2017) 10.1038/s41598-017-11115-1

